import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {Search,Upload,LayoutDashboard,Images,Check,CheckCheck,Download,WifiOff,X,ChevronRight,RefreshCw,FolderOpen,SlidersHorizontal,ArrowUpRight} from 'lucide-react';
import {registerSW} from 'virtual:pwa-register';
import './style.css';
import {Account, type Session, type User} from './Account';
type Candidate={filename:string;score:number|null;page_url:string;title:string;width:number;height:number;white_ratio:number;reason:string};
type Product={id:string;name:string;quantity:string;status:string;candidates:Candidate[];selected:number|null;reason:string};
type Job={archived?:boolean;id:string;name:string;created:string;status:string;processed:number;products:Product[]};
type InstallEvent=Event & {prompt:()=>Promise<void>};
function cacheJobs(_jobs:Job[]){/* Private catalogue data stays in memory, never in shared browser storage. */}
let updateSW:(reload?:boolean)=>Promise<void>;
function App(){
 const [jobs,setJobs]=useState<Job[]>([]),[active,setActive]=useState<string|null>(null),[tab,setTab]=useState('Workspace'),[filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[online,setOnline]=useState(navigator.onLine),[install,setInstall]=useState<InstallEvent|null>(null),[update,setUpdate]=useState(false),[review,setReview]=useState<string|null>(null),[authLoaded,setAuthLoaded]=useState(false),[user,setUser]=useState<User|null>(null),[durable,setDurable]=useState(false),[recovery,setRecovery]=useState(''),[installHelp,setInstallHelp]=useState(false),[inviteOpen,setInviteOpen]=useState(false),[inviteEmail,setInviteEmail]=useState(''),[inviteResult,setInviteResult]=useState<{email:string;link:string;delivery:string}|null>(null),[inviteBusy,setInviteBusy]=useState(false),[inviteError,setInviteError]=useState(''),[requestProcessing,setRequestProcessing]=useState(false),[uploadLimit,setUploadLimit]=useState(10_000_000);
 function acceptSession(data:Session){setUser(data.user);setDurable(data.durable);setRequestProcessing(!!data.request_processing);setUploadLimit(data.upload_limit||10_000_000);setAuthLoaded(true);if(data.recovery_code)setRecovery(data.recovery_code);setJobs([]);setActive(null);setReview(null);setError('')}
 useEffect(()=>{localStorage.removeItem('catalogue-jobs');if('caches' in window)caches.keys().then(keys=>Promise.all(keys.filter(k=>k==='review-images').map(k=>caches.delete(k))));fetch('/api/session').then(r=>{if(!r.ok)throw Error('Cannot load your session');return r.json()}).then(acceptSession).catch(()=>{setAuthLoaded(true);setError('Unable to connect. Check your connection and try again.')})},[]);
 async function signOut(){try{const r=await fetch('/api/logout',{method:'POST'});if(!r.ok)throw Error('Unable to sign out');setUser(null);setJobs([]);setActive(null);setReview(null);setRecovery('');setError('')}catch(e){setError((e as Error).message)}}
 const input=useRef<HTMLInputElement>(null),replacement=useRef<HTMLInputElement>(null);
 const job=jobs.find(j=>j.id===active),product=job?.products.find(p=>p.id===review);
 useEffect(()=>{const on=()=>setOnline(navigator.onLine);const prompt=(e:Event)=>{e.preventDefault();setInstall(e as InstallEvent)};window.addEventListener('online',on);window.addEventListener('offline',on);window.addEventListener('beforeinstallprompt',prompt);updateSW=registerSW({onNeedRefresh(){setUpdate(true)}});return()=>{window.removeEventListener('online',on);window.removeEventListener('offline',on);window.removeEventListener('beforeinstallprompt',prompt)}},[]);
 useEffect(()=>{let alive=true,refreshing=false;const refresh=async()=>{if(refreshing||!navigator.onLine||!user)return;refreshing=true;try{const response=await fetch('/api/jobs');if(response.status===401){if(alive){setUser(null);setJobs([]);setReview(null);setActive(null)};return}if(!response.ok)throw Error('Cannot connect to the image-search server.');const data:Job[]=await response.json();if(!alive)return;setJobs(data);const next=data.find(j=>['queued','running','cancelling'].includes(j.status));if(requestProcessing&&next){const result=await fetch(`/api/jobs/${next.id}/advance`,{method:'POST'});if(result.status===409)return;if(result.status===401){if(alive){setUser(null);setJobs([])};return}const updated=await result.json();if(!result.ok)throw Error(typeof updated.detail==='string'?updated.detail:'Search paused. Retry or resume the catalogue.');if(alive)setJobs(prev=>prev.map(j=>j.id===updated.id?updated:j))}}catch(e){if(alive)setError((e as Error).message)}finally{refreshing=false}};refresh();const t=setInterval(refresh,5000);return()=>{alive=false;clearInterval(t)}},[user?.id,requestProcessing]);
 async function exportImages(){if(!job)return;setBusy(true);setError('');try{const {zipSync}=await import('fflate');const files:Record<string,Uint8Array>={};for(const p of job.products){if(p.status!=='approved'||p.selected===null)continue;const name=p.candidates[p.selected].filename;const r=await fetch(`/api/jobs/${job.id}/images/${name}`);if(!r.ok)throw Error('Cannot download images. Check your session and try again.');files[name]=new Uint8Array(await r.arrayBuffer())}const bytes=zipSync(files,{level:0});const url=URL.createObjectURL(new Blob([new Uint8Array(bytes).buffer],{type:'application/zip'}));const a=document.createElement('a');a.href=url;a.download='catalogue.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}

 async function mutate(url:string,options:RequestInit){if(!online){setError('Reconnect to upload, search or change an image.');return}setBusy(true);setError('');try{const r=await fetch(url,options);const data=await r.json();if(r.status===401){setUser(null);setJobs([])}if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:'The request could not be completed.');setJobs(prev=>{const next=[data,...prev.filter(j=>j.id!==data.id)];cacheJobs(next);return next});setActive(data.id);return data}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function upload(file?:File){if(!file)return;if(file.size>uploadLimit){setError(`Choose a catalogue under ${uploadLimit/1_000_000} MB.`);return}const body=new FormData();body.append('file',file);await mutate('/api/jobs',{method:'POST',body});setTab('Workspace');if(input.current)input.current.value=''}
 function decide(action:string,candidate?:number){if(!job||!product)return;return mutate(`/api/jobs/${job.id}/products/${product.id}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,candidate})})}
 useEffect(()=>{if(!review)return;const previous=document.activeElement as HTMLElement;const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')setReview(null);if(e.key==='Tab'){const nodes=Array.from(document.querySelectorAll<HTMLElement>('.modal button:not(:disabled),.modal a[href],.modal input:not([hidden])'));const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',handler);return()=>{document.removeEventListener('keydown',handler);previous?.focus()}},[review]);
 const all=job?.products||[],approved=all.filter(p=>p.status==='approved').length,needs=all.filter(p=>p.status==='review').length;
 const visible=all.filter(p=>(filter==='all'||p.status===filter)&&(tab!=='Review queue'||p.status==='review')&&`${p.name} ${p.quantity}`.toLowerCase().includes(query.toLowerCase()));
 if(!authLoaded)return <div className="boot-screen"><img src="/brand-logo.png" alt="Catalogue Studio"/><p>Opening your studio…</p></div>;
 if(!user)return <><Account onSession={acceptSession}/>{error&&<div className="connection-error" role="alert">{error}<button onClick={()=>location.reload()}>Retry connection</button></div>}</>;
 return <div className="app"><aside><div className="brand"><img src="/brand-logo.png" alt="Product Image Finder by Siddique Sayed" /></div><div className="nav-label">YOUR STUDIO</div><nav>{[['Workspace',LayoutDashboard],['Catalogues',FolderOpen],['Review queue',Images]].map(([name,Icon])=><button key={name as string} className={tab===name?'selected':''} onClick={()=>{setTab(name as string);setFilter('all')}}><Icon size={19}/>{name as string}{name==='Review queue'&&needs>0&&<b>{needs}</b>}</button>)}</nav><div className="aside-note"><div className="mini-icon"><Search size={20}/></div><strong>A better catalogue,<br/>one image at a time.</strong><p>Find clean packshots. Review the details. Make them yours.</p></div><footer><div className="avatar">SS</div><div>{user.name}<small>Private workspace</small></div></footer></aside>
 <main><header><span>Studio <ChevronRight size={14}/> {tab}</span><div>{!online&&<span className="offline"><WifiOff size={15}/> Offline</span>}<button onClick={async()=>{if(install){await install.prompt();setInstall(null)}else setInstallHelp(true)}}><Download size={16}/> Install app</button>{user.id==='legacy'&&<button onClick={()=>{setInviteOpen(true);setInviteEmail('');setInviteResult(null);setInviteError('')}}>Invite by email</button>}<button onClick={signOut}>Sign out</button><div className="avatar">SS</div></div></header>
 {!online&&<div className="notice"><WifiOff size={18}/> You’re offline. Reconnect to load your private catalogues, search, upload or review.</div>}{update&&<div className="notice">A new version is ready.<button onClick={()=>updateSW(true)}>Update app</button></div>}{error&&<div className="error" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
 {!durable&&<div className="notice storage-notice">Demo storage: accounts and uploads can be lost when this server restarts. Export your work. Connect a database before inviting customers.</div>}
 <section className="page-heading"><div><div className="eyebrow">THE CATALOGUE STUDIO</div><h1>{tab==='Review queue'?'Every detail matters.':tab==='Catalogues'?'Your catalogues.':'Good images. Better products.'}</h1><p>{tab==='Review queue'?'Check the product, packaging and pack size before you approve.':'Turn your product list into a catalogue worth looking at.'}</p></div><button className="primary" disabled={busy||!online} onClick={()=>input.current?.click()}><Upload size={17}/> Upload catalogue</button></section>
 <input ref={input} type="file" accept=".csv,.xlsx" hidden onChange={e=>upload(e.target.files?.[0])}/>
 {tab==='Catalogues'?<section className="catalogues"><div className="section-title"><h2>All catalogues</h2><span>{jobs.length} catalogues</span></div>{jobs.length===0?<div className="empty"><FolderOpen/><h3>No catalogues yet</h3><p>Upload your first CSV or Excel catalogue to begin.</p></div>:jobs.map(j=><button className="job-row" key={j.id} onClick={()=>{setActive(j.id);setTab('Workspace')}}><div className="file-icon"><FolderOpen/></div><div><strong>{j.name}</strong><small>{new Date(j.created).toLocaleDateString()} · {j.products.length} products</small></div><span className={'badge '+j.status}>{j.archived?'Archived':j.status}</span><ChevronRight/></button>)}</section>:<>
 <div className="stats"><div><span><Images size={17}/> Products</span><strong>{all.length.toString().padStart(2,'0')}</strong><small>{job?'In this catalogue':'Upload a catalogue to begin'}</small></div><div><span><CheckCheck size={17}/> Approved</span><strong>{approved.toString().padStart(2,'0')}<i>ready to export</i></strong><small>Checked and selected by you</small></div><div><span><Search size={17}/> Needs review</span><strong>{needs.toString().padStart(2,'0')}</strong><small>Waiting for your final check</small></div></div>
 {!job?<div className="onboarding"><div className="upload-zone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();upload(e.dataTransfer.files[0])}}><div className="upload-icon"><Upload size={27}/></div><h2>Your next catalogue starts here.</h2><p>Drop a product list here, or choose a file.<br/>We’ll detect product names and pack sizes for you.</p><button className="primary" disabled={busy||!online} onClick={()=>input.current?.click()}>Choose catalogue</button><small>CSV or XLSX · Up to 500 products · {uploadLimit/1_000_000} MB maximum</small></div><div className="how"><div className="eyebrow">FROM LIST TO LIBRARY</div>{[['01','Bring your products','Upload a sheet with Product Name and Quantity columns.'],['02','Find the right images','Search for clean, high resolution product packshots.'],['03','Give it your approval','Check each match, then export your images and report.']].map(([n,t,d])=><div key={n}><span>{n}</span><section><h3>{t}</h3><p>{d}</p></section></div>)}<a href="/sample.csv" download>Download sample catalogue <Download size={15}/></a></div></div>:<>
 <section className="catalogue-head"><div className="file-icon"><FolderOpen size={22}/></div><div><h2>{job.name}</h2><p>{all.length} products · <span>{job.status}</span></p></div><select aria-label="Select catalogue" value={active||''} onChange={e=>setActive(e.target.value)}>{jobs.map(j=><option key={j.id} value={j.id}>{j.name}</option>)}</select>{!job.archived&&['ready','interrupted','cancelled'].includes(job.status)&&<button className="primary" disabled={busy||!online} onClick={()=>mutate(`/api/jobs/${job.id}/start`,{method:'POST'})}><Search size={17}/> {job.status!=='ready'?'Resume search':'Find images'}</button>}{['running','queued'].includes(job.status)&&<button disabled={busy||!online} onClick={()=>mutate(`/api/jobs/${job.id}/cancel`,{method:'POST'})}>Pause search</button>}{!['running','queued','cancelling'].includes(job.status)&&<button disabled={busy||!online} onClick={async()=>{await mutate(`/api/jobs/${job.id}/archive`,{method:'POST'});setActive(null);setTab('Catalogues')}}>{job.archived?'Restore catalogue':'Archive catalogue'}</button>}{['complete','interrupted','cancelled'].includes(job.status)&&all.some(p=>!p.candidates.length)&&<button disabled={busy||!online} onClick={()=>mutate(`/api/jobs/${job.id}/retry`,{method:'POST'})}>Retry missing images</button>}</section>
 {['running','queued','cancelling'].includes(job.status)&&<div className="progress"><div><RefreshCw size={16} className="spin"/> {job.status==='cancelling'?'Stopping search…':'Finding your product images'} <span>{job.processed} / {all.length}</span></div><progress max={all.length} value={job.processed}/>{requestProcessing&&<p>Keep this app open while searching. Saved progress continues when you reopen it. Pause and review changes may wait for the current product to finish.</p>}</div>}
 <section className="library"><div className="section-title"><h2>{tab==='Review queue'?'Review queue':'Product library'}</h2><div className="exports">{['csv','xlsx','zip'].map(k=><button key={k} disabled={!online||busy} onClick={()=>k==='zip'?exportImages():window.location.assign(`/api/jobs/${job.id}/export/${k}`)}><Download size={14}/> {k==='zip'?'Approved images':k.toUpperCase()}</button>)}</div></div><div className="toolbar"><div className="filters">{['all','review','approved','rejected'].map(f=><button key={f} className={filter===f?'current':''} onClick={()=>setFilter(f)}>{f==='all'?'All products':f==='review'?'Needs review':f}</button>)}</div><label className="search"><Search size={16}/><input placeholder="Search products" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
 <div className="grid">{visible.map(p=>{const c=p.selected===null?null:p.candidates[p.selected];return <button key={p.id} className="product-card" onClick={()=>setReview(p.id)}><div className="image-area">{c?<img src={`/api/jobs/${job.id}/images/${c.filename}`} alt={p.name}/>:<div className="image-placeholder"><Images size={30}/><span>{p.status==='pending'?'Waiting for search':'Add an image'}</span></div>}<span className={'badge '+p.status}>{p.status==='review'?'Needs review':p.status}</span>{c?.score!=null&&<span className="score">{c.score}<small>match score</small></span>}</div><div className="product-info"><h3>{p.name}</h3><p>{p.quantity}<span>{c?`${c.width||'—'} × ${c.height||'—'}`:'No image selected'}</span></p>{(p.reason||c?.reason)&&<small className="image-warning">{p.reason||c?.reason}</small>}</div></button>})}</div>{visible.length===0&&<div className="empty"><CheckCheck/><h3>{tab==='Review queue'?'You’re all caught up.':'No products in this view.'}</h3><p>Results will appear as the search progresses.</p></div>}</section></>}
 {!job&&jobs.length>0&&<section className="recent"><div className="section-title"><h2>Recent catalogues</h2><button onClick={()=>setTab('Catalogues')}>View catalogues</button></div>{jobs.filter(j=>!j.archived).slice(0,3).map(j=><button className="job-row" key={j.id} onClick={()=>setActive(j.id)}><FolderOpen/><div><strong>{j.name}</strong><small>{j.products.length} products</small></div><span className="badge">{j.status}</span><ChevronRight/></button>)}</section>}
 </>}
 <div className="credit">Designed & built by <strong>Siddique Sayed</strong><span>Product Image Finder / v2.0 beta</span></div></main>
 {inviteOpen&&<div className="modal-backdrop"><section className="modal recovery" role="dialog" aria-modal="true" aria-label="Invite by email"><h2>Invite someone to their own studio</h2><p>Enter their email address. Their private signup link works once and expires in seven days.</p><form onSubmit={async e=>{e.preventDefault();setInviteBusy(true);setInviteError('');setInviteResult(null);try{const r=await fetch('/api/invites',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:inviteEmail})});const data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:'Could not create invitation');setInviteResult(data)}catch(error){setInviteError((error as Error).message)}finally{setInviteBusy(false)}}}><label>Recipient email<input type="email" autoFocus required maxLength={254} value={inviteEmail} onChange={e=>setInviteEmail(e.target.value)}/></label><button className="primary" disabled={inviteBusy||!online}>{inviteBusy?'Preparing invitation…':'Send invitation'}</button></form>{inviteError&&<p className="error" role="alert">{inviteError}</p>}{inviteResult&&<div role="status"><p>{inviteResult.delivery==='sent'?'Invitation email sent to '+inviteResult.email+'.':inviteResult.delivery==='failed'?'Email sending failed. You can send the private link yourself below.':'Automatic email is awaiting Gmail setup. You can send this invitation from Gmail below.'}</p><a href={'https://mail.google.com/mail/?view=cm&fs=1&to='+encodeURIComponent(inviteResult.email)+'&su='+encodeURIComponent('Your invitation to Product Image Finder')+'&body='+encodeURIComponent('Siddique has invited you to your own private workspace. Create your account: '+inviteResult.link+'\n\nThis link works once, expires in seven days, and is only for '+inviteResult.email+'.')} target="_blank" rel="noreferrer">Open invitation in Gmail</a><button onClick={async()=>{try{await navigator.clipboard.writeText(inviteResult.link)}catch{setInviteError('Clipboard unavailable. Open the invitation in Gmail to copy the link.')}}}>Copy private link</button></div>}<p>They’ll choose their own password. Each account has a private catalogue workspace.</p><button disabled={inviteBusy} onClick={()=>setInviteOpen(false)}>Done</button></section></div>}
 {recovery&&<div className="modal-backdrop"><section className="modal recovery" role="dialog" aria-modal="true" aria-label="Save recovery code"><h2>Keep your recovery code safe</h2><p>This is shown once. You’ll need it to reset your password without an email service.</p><code>{recovery}</code><button onClick={()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([recovery],{type:'text/plain'}));a.download='studio-recovery-code.txt';a.click();URL.revokeObjectURL(a.href)}}>Download code</button><button className="primary" onClick={()=>setRecovery('')}>I’ve saved my code</button></section></div>}
 {installHelp&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="Install the app"><button className="close" aria-label="Close install instructions" onClick={()=>setInstallHelp(false)}><X/></button><h2>Your studio, on your home screen</h2><p><strong>iPhone / iPad:</strong> open this site in Safari, tap Share, then Add to Home Screen.</p><p><strong>Android:</strong> open in Chrome, choose Install app or Add to Home screen from the menu.</p><p><strong>Desktop:</strong> use Chrome or Edge and select the install icon in the address bar.</p><p>Installation is free. Searching and your private catalogues require an internet connection.</p><button onClick={()=>setInstallHelp(false)}>Got it</button></section></div>}
 {product&&job&&<div className="modal-backdrop" onClick={()=>setReview(null)}><section className="modal" role="dialog" aria-modal="true" aria-label={'Review '+product.name} onClick={e=>e.stopPropagation()}><button className="close" autoFocus aria-label="Close review" onClick={()=>setReview(null)}><X/></button><div className="eyebrow">PRODUCT REVIEW</div><h2>{product.name}</h2><p>{product.quantity}</p><div className="review-image">{product.selected!==null?<img src={`/api/jobs/${job.id}/images/${product.candidates[product.selected].filename}`} alt={product.name}/>:<Images size={50}/>}</div>{product.reason&&<p>{product.reason}</p>}<div className="candidates">{product.candidates.map((c,i)=><button key={c.filename} aria-label={`Select candidate ${i+1}`} className={product.selected===i?'chosen':''} disabled={busy||!online} onClick={()=>decide('select',i)}><img src={`/api/jobs/${job.id}/images/${c.filename}`} alt={`Candidate ${i+1}`}/><span>{c.score??'Uploaded'}</span></button>)}</div>{product.selected!==null&&<div className="details"><span>Resolution <b>{product.candidates[product.selected].width||'—'} × {product.candidates[product.selected].height||'—'}</b></span><span>White border <b>{Math.round(product.candidates[product.selected].white_ratio*100)}%</b></span>{product.candidates[product.selected].page_url&&<a href={product.candidates[product.selected].page_url} target="_blank" rel="noreferrer">View original source <ArrowUpRight size={15}/></a>}</div>}{product.selected!==null&&product.candidates[product.selected].reason&&<p className="image-warning" role="status">{product.candidates[product.selected].reason}</p>}<p className="review-note">Match scores are automated estimates. Check the exact product, variant, pack size and image usage rights.</p><input ref={replacement} type="file" accept="image/*" hidden onChange={async e=>{const file=e.target.files?.[0];if(file){const body=new FormData();body.append('file',file);await mutate(`/api/jobs/${job.id}/products/${product.id}/image`,{method:'POST',body});if(replacement.current)replacement.current.value=''}}}/><div className="modal-actions"><button disabled={busy||!online||['running','queued','cancelling'].includes(job.status)} onClick={()=>replacement.current?.click()}><Upload size={16}/> Replace</button><button disabled={busy||!online||product.status==='pending'} onClick={()=>decide('reject')}>Reject</button><button className="primary" disabled={busy||!online||product.selected===null} onClick={async()=>{if(await decide('approve'))setReview(null)}}><Check size={17}/> Approve image</button></div></section></div>}
 </div>
}
createRoot(document.getElementById('root')!).render(<App/>);
