import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {Search,Upload,LayoutDashboard,Images,Check,CheckCheck,Download,WifiOff,X,ChevronRight,RefreshCw,FolderOpen,SlidersHorizontal,ArrowUpRight} from 'lucide-react';
import {registerSW} from 'virtual:pwa-register';
import './style.css';
type Candidate={filename:string;score:number|null;page_url:string;title:string;width:number;height:number;white_ratio:number;reason:string};
type Product={id:string;name:string;quantity:string;status:string;candidates:Candidate[];selected:number|null;reason:string};
type Job={id:string;name:string;created:string;status:string;processed:number;products:Product[]};
type InstallEvent=Event & {prompt:()=>Promise<void>};
function cacheJobs(jobs:Job[]){try{localStorage.setItem('catalogue-jobs',JSON.stringify(jobs))}catch{/* Keep current session usable when browser storage is full. */}}
let updateSW:(reload?:boolean)=>Promise<void>;
function App(){
 const [jobs,setJobs]=useState<Job[]>(()=>{try{return JSON.parse(localStorage.getItem('catalogue-jobs')||'[]')}catch{return []}}),[active,setActive]=useState<string|null>(null),[tab,setTab]=useState('Workspace'),[filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[online,setOnline]=useState(navigator.onLine),[install,setInstall]=useState<InstallEvent|null>(null),[update,setUpdate]=useState(false),[review,setReview]=useState<string|null>(null),[needsLogin,setNeedsLogin]=useState(false),[password,setPassword]=useState('');
 const input=useRef<HTMLInputElement>(null),replacement=useRef<HTMLInputElement>(null);
 const job=jobs.find(j=>j.id===active),product=job?.products.find(p=>p.id===review);
 useEffect(()=>{const on=()=>setOnline(navigator.onLine);const prompt=(e:Event)=>{e.preventDefault();setInstall(e as InstallEvent)};window.addEventListener('online',on);window.addEventListener('offline',on);window.addEventListener('beforeinstallprompt',prompt);updateSW=registerSW({onNeedRefresh(){setUpdate(true)}});return()=>{window.removeEventListener('online',on);window.removeEventListener('offline',on);window.removeEventListener('beforeinstallprompt',prompt)}},[]);
 useEffect(()=>{let alive=true;const refresh=async()=>{if(!navigator.onLine)return;try{const response=await fetch('/api/jobs');if(response.status===401){if(alive)setNeedsLogin(true);return}if(!response.ok)throw Error('Cannot connect to the image-search server.');const data=await response.json();if(alive){setJobs(data);cacheJobs(data)}}catch(e){if(alive)setError((e as Error).message)}};refresh();const t=setInterval(refresh,3000);return()=>{alive=false;clearInterval(t)}},[]);
 async function mutate(url:string,options:RequestInit){if(!online){setError('Reconnect to upload, search or change an image.');return}setBusy(true);setError('');try{const r=await fetch(url,options);const data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:'The request could not be completed.');setJobs(prev=>{const next=[data,...prev.filter(j=>j.id!==data.id)];cacheJobs(next);return next});setActive(data.id);return data}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function signIn(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(!r.ok)throw Error('Incorrect password. Please try again.');setNeedsLogin(false);setPassword('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function upload(file?:File){if(!file)return;const body=new FormData();body.append('file',file);await mutate('/api/jobs',{method:'POST',body});setTab('Workspace');if(input.current)input.current.value=''}
 function decide(action:string,candidate?:number){if(!job||!product)return;return mutate(`/api/jobs/${job.id}/products/${product.id}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,candidate})})}
 useEffect(()=>{if(!review)return;const previous=document.activeElement as HTMLElement;const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')setReview(null);if(e.key==='Tab'){const nodes=Array.from(document.querySelectorAll<HTMLElement>('.modal button:not(:disabled),.modal a[href],.modal input:not([hidden])'));const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',handler);return()=>{document.removeEventListener('keydown',handler);previous?.focus()}},[review]);
 const all=job?.products||[],approved=all.filter(p=>p.status==='approved').length,needs=all.filter(p=>p.status==='review').length;
 const visible=all.filter(p=>(filter==='all'||p.status===filter)&&(tab!=='Review queue'||p.status==='review')&&`${p.name} ${p.quantity}`.toLowerCase().includes(query.toLowerCase()));
 return <div className="app"><aside><div className="brand"><img src="/brand-logo.png" alt="Product Image Finder by Siddique Sayed" /></div><div className="nav-label">YOUR STUDIO</div><nav>{[['Workspace',LayoutDashboard],['Catalogues',FolderOpen],['Review queue',Images]].map(([name,Icon])=><button key={name as string} className={tab===name?'selected':''} onClick={()=>{setTab(name as string);setFilter('all')}}><Icon size={19}/>{name as string}{name==='Review queue'&&needs>0&&<b>{needs}</b>}</button>)}</nav><div className="aside-note"><div className="mini-icon"><Search size={20}/></div><strong>A better catalogue,<br/>one image at a time.</strong><p>Find clean packshots. Review the details. Make them yours.</p></div><footer><div className="avatar">SS</div><div>Siddique Sayed<small>Creator & developer</small></div></footer></aside>
 <main><header><span>Studio <ChevronRight size={14}/> {tab}</span><div>{!online&&<span className="offline"><WifiOff size={15}/> Offline</span>}{install&&<button onClick={async()=>{await install.prompt();setInstall(null)}}><Download size={16}/> Install app</button>}<div className="avatar">SS</div></div></header>
 {!online&&<div className="notice"><WifiOff size={18}/> You’re offline. Saved results are available; reconnect to search, upload or review.</div>}{update&&<div className="notice">A new version is ready.<button onClick={()=>updateSW(true)}>Update app</button></div>}{error&&<div className="error" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
 <section className="page-heading"><div><div className="eyebrow">THE CATALOGUE STUDIO</div><h1>{tab==='Review queue'?'Every detail matters.':tab==='Catalogues'?'Your catalogues.':'Good images. Better products.'}</h1><p>{tab==='Review queue'?'Check the product, packaging and pack size before you approve.':'Turn your product list into a catalogue worth looking at.'}</p></div><button className="primary" disabled={busy||!online} onClick={()=>input.current?.click()}><Upload size={17}/> Upload catalogue</button></section>
 <input ref={input} type="file" accept=".csv,.xlsx" hidden onChange={e=>upload(e.target.files?.[0])}/>
 {tab==='Catalogues'?<section className="catalogues"><div className="section-title"><h2>All catalogues</h2><span>{jobs.length} catalogues</span></div>{jobs.length===0?<div className="empty"><FolderOpen/><h3>No catalogues yet</h3><p>Upload your first CSV or Excel catalogue to begin.</p></div>:jobs.map(j=><button className="job-row" key={j.id} onClick={()=>{setActive(j.id);setTab('Workspace')}}><div className="file-icon"><FolderOpen/></div><div><strong>{j.name}</strong><small>{new Date(j.created).toLocaleDateString()} · {j.products.length} products</small></div><span className={'badge '+j.status}>{j.status}</span><ChevronRight/></button>)}</section>:<>
 <div className="stats"><div><span><Images size={17}/> Products</span><strong>{all.length.toString().padStart(2,'0')}</strong><small>{job?'In this catalogue':'Upload a catalogue to begin'}</small></div><div><span><CheckCheck size={17}/> Approved</span><strong>{approved.toString().padStart(2,'0')}<i>ready to export</i></strong><small>Checked and selected by you</small></div><div><span><Search size={17}/> Needs review</span><strong>{needs.toString().padStart(2,'0')}</strong><small>Waiting for your final check</small></div></div>
 {!job?<div className="onboarding"><div className="upload-zone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();upload(e.dataTransfer.files[0])}}><div className="upload-icon"><Upload size={27}/></div><h2>Your next catalogue starts here.</h2><p>Drop a product list here, or choose a file.<br/>We’ll detect product names and pack sizes for you.</p><button className="primary" disabled={busy||!online} onClick={()=>input.current?.click()}>Choose catalogue</button><small>CSV or XLSX · Up to 500 products · 10 MB maximum</small></div><div className="how"><div className="eyebrow">FROM LIST TO LIBRARY</div>{[['01','Bring your products','Upload a sheet with Product Name and Quantity columns.'],['02','Find the right images','Search for clean, high resolution product packshots.'],['03','Give it your approval','Check each match, then export your images and report.']].map(([n,t,d])=><div key={n}><span>{n}</span><section><h3>{t}</h3><p>{d}</p></section></div>)}<a href="/sample.csv" download>Download sample catalogue <Download size={15}/></a></div></div>:<>
 <section className="catalogue-head"><div className="file-icon"><FolderOpen size={22}/></div><div><h2>{job.name}</h2><p>{all.length} products · <span>{job.status}</span></p></div><select aria-label="Select catalogue" value={active||''} onChange={e=>setActive(e.target.value)}>{jobs.map(j=><option key={j.id} value={j.id}>{j.name}</option>)}</select>{['ready','interrupted'].includes(job.status)&&<button className="primary" disabled={busy||!online} onClick={()=>mutate(`/api/jobs/${job.id}/start`,{method:'POST'})}><Search size={17}/> {job.status==='interrupted'?'Resume search':'Find images'}</button>}</section>
 {['running','queued'].includes(job.status)&&<div className="progress"><div><RefreshCw size={16} className="spin"/> Finding your product images <span>{job.processed} / {all.length}</span></div><progress max={all.length} value={job.processed}/></div>}
 <section className="library"><div className="section-title"><h2>{tab==='Review queue'?'Review queue':'Product library'}</h2><div className="exports">{['csv','xlsx','zip'].map(k=><button key={k} disabled={!online} onClick={()=>window.location.assign(`/api/jobs/${job.id}/export/${k}`)}><Download size={14}/> {k==='zip'?'Approved images':k.toUpperCase()}</button>)}</div></div><div className="toolbar"><div className="filters">{['all','review','approved','rejected'].map(f=><button key={f} className={filter===f?'current':''} onClick={()=>setFilter(f)}>{f==='all'?'All products':f==='review'?'Needs review':f}</button>)}</div><label className="search"><Search size={16}/><input placeholder="Search products" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
 <div className="grid">{visible.map(p=>{const c=p.selected===null?null:p.candidates[p.selected];return <button key={p.id} className="product-card" onClick={()=>setReview(p.id)}><div className="image-area">{c?<img src={`/api/jobs/${job.id}/images/${c.filename}`} alt={p.name}/>:<div className="image-placeholder"><Images size={30}/><span>{p.status==='pending'?'Waiting for search':'Add an image'}</span></div>}<span className={'badge '+p.status}>{p.status==='review'?'Needs review':p.status}</span>{c?.score!=null&&<span className="score">{c.score}<small>match score</small></span>}</div><div className="product-info"><h3>{p.name}</h3><p>{p.quantity}<span>{c?`${c.width||'—'} × ${c.height||'—'}`:'No image selected'}</span></p></div></button>})}</div>{visible.length===0&&<div className="empty"><CheckCheck/><h3>{tab==='Review queue'?'You’re all caught up.':'No products in this view.'}</h3><p>Results will appear as the search progresses.</p></div>}</section></>}
 {!job&&jobs.length>0&&<section className="recent"><div className="section-title"><h2>Recent catalogues</h2><button onClick={()=>setTab('Catalogues')}>View catalogues</button></div>{jobs.slice(0,3).map(j=><button className="job-row" key={j.id} onClick={()=>setActive(j.id)}><FolderOpen/><div><strong>{j.name}</strong><small>{j.products.length} products</small></div><span className="badge">{j.status}</span><ChevronRight/></button>)}</section>}
 </>}
 <div className="credit">Designed & built by <strong>Siddique Sayed</strong><span>Product Image Finder / v1.0</span></div></main>
 {needsLogin&&<div className="modal-backdrop"><form className="modal login" onSubmit={signIn}><img src="/brand-logo.png" alt="Product Image Finder by Siddique Sayed"/><h2>Your catalogue studio</h2><p>Enter your app password to continue.</p><label>Password<input type="password" autoComplete="current-password" autoFocus required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<button className="primary" disabled={busy||!online} type="submit">Sign in</button></form></div>}
 {product&&job&&<div className="modal-backdrop" onClick={()=>setReview(null)}><section className="modal" role="dialog" aria-modal="true" aria-label={'Review '+product.name} onClick={e=>e.stopPropagation()}><button className="close" autoFocus aria-label="Close review" onClick={()=>setReview(null)}><X/></button><div className="eyebrow">PRODUCT REVIEW</div><h2>{product.name}</h2><p>{product.quantity}</p><div className="review-image">{product.selected!==null?<img src={`/api/jobs/${job.id}/images/${product.candidates[product.selected].filename}`} alt={product.name}/>:<Images size={50}/>}</div>{product.reason&&<p>{product.reason}</p>}<div className="candidates">{product.candidates.map((c,i)=><button key={c.filename} aria-label={`Select candidate ${i+1}`} className={product.selected===i?'chosen':''} disabled={busy||!online} onClick={()=>decide('select',i)}><img src={`/api/jobs/${job.id}/images/${c.filename}`} alt={`Candidate ${i+1}`}/><span>{c.score??'Uploaded'}</span></button>)}</div>{product.selected!==null&&<div className="details"><span>Resolution <b>{product.candidates[product.selected].width||'—'} × {product.candidates[product.selected].height||'—'}</b></span><span>White border <b>{Math.round(product.candidates[product.selected].white_ratio*100)}%</b></span>{product.candidates[product.selected].page_url&&<a href={product.candidates[product.selected].page_url} target="_blank" rel="noreferrer">View original source <ArrowUpRight size={15}/></a>}</div>}<p className="review-note">Match scores are automated estimates. Check the exact product, variant, pack size and image usage rights.</p><input ref={replacement} type="file" accept="image/*" hidden onChange={async e=>{const file=e.target.files?.[0];if(file){const body=new FormData();body.append('file',file);await mutate(`/api/jobs/${job.id}/products/${product.id}/image`,{method:'POST',body});if(replacement.current)replacement.current.value=''}}}/><div className="modal-actions"><button disabled={busy||!online||product.status==='pending'} onClick={()=>replacement.current?.click()}><Upload size={16}/> Replace</button><button disabled={busy||!online||product.status==='pending'} onClick={()=>decide('reject')}>Reject</button><button className="primary" disabled={busy||!online||product.selected===null} onClick={async()=>{if(await decide('approve'))setReview(null)}}><Check size={17}/> Approve image</button></div></section></div>}
 </div>
}
createRoot(document.getElementById('root')!).render(<App/>);
